apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-subodh-db-pvc
  namespace: test-subodh
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
